### ISSUE TITLE
Cicero-CLI: utcOffset and currentTime concurrent usage gives error

### ISSUE THREAD

**Issue by K-Kumar-01** [accordproject/cicero#740] opened 2022-05-22 02:39 UTC
# Bug Report 🐛

When using the command `cicero parse --template <template> --sample <sample> --utcOffset 2 --currentTime "08:06:00"`, instead of succesfully executing the command, we get an error.

## Expected Behavior

The command should run without any errors.

## Current Behavior

` ERROR: Cannot set current time to '08:06:00' with UTC offset '2'` is received currently.

## Steps to Reproduce

1. Install cicero-cli
2. Run the command mentioned above

## Screenshots
![Screenshot from 2022-05-22 08-06-04](https://user-images.githubusercontent.com/59891164/169675856-a6574d7c-dbb7-4eb2-9698-d6f030a4588c.png)

### Desktop
 - OS: [e.g. macOS] Zorin OS

**Comment by Ayman161803** [comment] 2022-05-22 07:19
The problem is with ``DateTimeUtil`` module of ``concerto-core`` package [here](https://github.com/accordproject/concerto/blob/7ebf036f3fa7a1e532f0bafc19b787144d2104dd/packages/concerto-core/lib/datetimeutil.js#L38). The string ``currentTime`` here  should is expected to be in standard UTC format. We can either modify the expected string to a more convenient format such as ``DD-MM-YYYY HH:MM:SS`` or retain the format as is. Can I have this issue assigned to me in case it is decided to shift to a more convenient date-time format?

**Comment by mttrbrts** [comment] 2022-05-22 15:23
We should enforce use of a UTC format value, however the error message can be improved to guide the user.

**Comment by K-Kumar-01** [comment] 2022-05-22 15:31
> We should enforce use of a UTC format value, however the error message can be improved to guide the user.

Should we ask users the format in which they want to enter the date :thinking: ? There are different formats which can provide fleixibility. By default, this can be kept to utc

**Comment by mttrbrts** [comment] 2022-05-26 14:51
> Should we ask users the format in which they want to enter the date 🤔 ? 

IMO, I say no. We should provide a well-defined format that works for everyone. There's a risk that increased flexibility means increased complexity in this case.

**Comment by Ayman161803** [comment] 2022-08-08 12:44
This Issue can be closed after accordproject/concerto#430 @mttrbrts

**Comment by mttrbrts** [comment] 2022-08-09 20:17
> This Issue can be closed after accordproject/concerto#430 @mttrbrts 

Thank you, closing!

**Closed** 2022-08-09 20:17 UTC
