### ISSUE TITLE
Templates with tab characters do not roundtrip between parse and generateText

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero#441] opened 2019-10-15 11:38 UTC
If a template contains the tab character (\t) then we when `parse` is called a JSON data is created, however if you subsequently call `generateText` with the JSON data then tab characters in the template are expanded as `\t`.

**To Reproduce**
1. Download the attached template
2. Unzip
3. Install Cicero CLI
4. cicero parse --out data.json
5. cicero generateText --data data.json

**Expected behavior**
Should roundtrip, or somehow strip tabs.

**Comment by dselman** [comment] 2019-10-15 11:39
[goldman-nda@0.1.2.cta.zip](https://github.com/accordproject/cicero/files/3729020/goldman-nda%400.1.2.cta.zip)

**Comment by dselman** [comment] 2019-10-15 11:39
@jeromesimeon another whitespace issue in 0.13.4

**Comment by dselman** [comment] 2019-10-15 12:14
[whitespace-test@0.1.2.cta.zip](https://github.com/accordproject/cicero/files/3729141/whitespace-test%400.1.2.cta.zip)

**Comment by jeromesimeon** [comment] 2019-10-15 12:46
This specific sample works on the `0.20-alpha` branch, in the sense that the result of `generateText` can be parsed again and yields the same JSON:

```
bash-3.2$ ~/git/cicero/packages/cicero-cli/index.js --version 
0.20.0-alpha.2
bash-3.2$ ~/git/cicero/packages/cicero-cli/index.js parse --out data.json
08:44:59 - info: Using current directory as template folder
08:44:59 - info: Loading a default sample.md file.
08:45:01 - info: Creating file: data.json
08:45:01 - info:
{
  "$class": "io.clause.demo.nda.GoldmanNDAClause",
  "contractId": "e3f4fd80-d405-4357-bee0-18c33d207bc7",
  "clideNumber": "CPIP-2019-004991",
  "tvetNumber": "36917",
  "vendorName": {
    "$class": "org.accordproject.cicero.contract.AccordParty",
    "partyId": "Bar"
  },
  "vendorAddress": "Baz",
  "accountName": {
    "$class": "org.accordproject.cicero.contract.AccordParty",
    "partyId": "Boop"
  },
  "accountAddress": "Betty",
  "effectiveDate": "2019-10-03T00:00:00.000-04:00"
}
bash-3.2$ ~/git/cicero/packages/cicero-cli/index.js generateText --out sample2.md 
08:45:13 - info: Using current directory as template folder
08:45:13 - info: Loading a default data.json file.
08:45:14 - info: Creating file: sample2.md
08:45:14 - info: Clide#: "CPIP-2019-004991"
Tvet#: "36917"

Vendor:	"Bar"
"Baz"

Foo:	"Boop"
"Betty"

Effective Date: 10/03/2019
bash-3.2$ ~/git/cicero/packages/cicero-cli/index.js parse --sample sample2.md 
08:45:21 - info: Using current directory as template folder
08:45:23 - info:
{
  "$class": "io.clause.demo.nda.GoldmanNDAClause",
  "contractId": "4b13d975-83bd-4f52-ad8c-a28dce2011dc",
  "clideNumber": "CPIP-2019-004991",
  "tvetNumber": "36917",
  "vendorName": {
    "$class": "org.accordproject.cicero.contract.AccordParty",
    "partyId": "Bar"
  },
  "vendorAddress": "Baz",
  "accountName": {
    "$class": "org.accordproject.cicero.contract.AccordParty",
    "partyId": "Boop"
  },
  "accountAddress": "Betty",
  "effectiveDate": "2019-10-03T00:00:00.000-04:00"
}
bash-3.2$
```

**Comment by jeromesimeon** [comment] 2019-10-17 21:16
Fixed in master now.

**Closed by jeromesimeon** 2019-10-17 21:17 UTC
Labels: 0.20-alpha, Difficulty: Challenging, Type: Bug 🐛

**Comment by jeromesimeon** [comment] 2019-10-17 21:18
Duplicate of #353
