### ISSUE TITLE
Parser Manager loses reference to `window` when a template is loaded in a JavaScript `Worker`

### ISSUE THREAD

**Issue by algomaster99** [accordproject/cicero#556] opened 2020-06-15 15:29 UTC
**Describe the bug**
Parser Manager loses reference to `window` when a template is loaded in a JavaScript `Worker`. @dselman suspects it is because of [this line](https://github.com/accordproject/cicero/blob/master/packages/cicero-core/src/parsermanager.js#L42).

**To Reproduce**
1. Load a template in a `Worker`.

**Expected behavior**
I should get an object of the template.

**Screenshots**
```
1    /***/ "./node_modules/@accordproject/cicero-core/lib/compiled_template.js":
2    /*!**************************************************************************!*\
3      !*** ./node_modules/@accordproject/cicero-core/lib/compiled_template.js ***!
4      \**************************************************************************/
5    /*! no static exports found */
6    /***/ (function(module, exports) {
7    (function() {(window.nunjucksPrecompiled = window.nunjucksPrecompiled || {})["template.ne"] = (function() {
8    function root(env, context, frame, runtime, cb) {
9    var lineno = 0;
10  var colno = 0;
11  var output = "";
12  try {
      var parentTemplate = null;
```
**Line 7** throw `window` is not defined,

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge

**Additional context**
I was trying to load a template in the word add-in using `Template.fromUrl` method but the application kept crashing. I suspect because this loading operation was taking too long. Hence, I decided to run this as a background process using `Worker`. But it kept throwing the above error when I tried to import utilities like `Template` from `cicero-core`.

**Comment by irmerk** [comment] 2020-06-15 18:43
Following up after a call with @algomaster99, @jeromesimeon, @dselman, and @DianaLease, this will likely be fixed when the new parser (#547) is implemented.

**Comment by jeromesimeon** [comment] 2020-06-15 19:40
@algomaster99 @irmerk A sample to reproduce the issue would be useful (to check that it does get fixed with the new parser).

**Comment by algomaster99** [comment] 2020-06-15 19:46
@jeromesimeon It is just these two lines
```
Template.fromUrl('https://templates.accordproject.org/archives/acceptance-of-delivery@0.13.2.cta').then(template => {
      console.log(template)
    })
```
If it successfully returns a `template` in the console, the issue will be fixed.

**Comment by jeromesimeon** [comment] 2020-06-15 19:54
> @jeromesimeon It is just these two lines
> 
> ```
> Template.fromUrl('https://templates.accordproject.org/archives/acceptance-of-delivery@0.13.2.cta').then(template => {
>       console.log(template)
>     })
> ```
> 
> If it successfully returns a `template` in the console, the issue will be fixed.

That line usually works well on its own. I'm assuming there is a "web worker" thingie that should be around it?

**Comment by algomaster99** [comment] 2020-06-15 20:29
@jeromesimeon oh yeah
So one should be successfully able to import `@accordproject/cicero-core` in workers. And there shouldn't be any references to `window` in the precompiled files.

**Comment by jeromesimeon** [comment] 2020-06-15 20:32
> @jeromesimeon oh yeah
> So one should be successfully able to import `@accordproject/cicero-core` in workers. And there shouldn't be any references to `window` in the precompiled files.

A sample test for that would help.

**Comment by algomaster99** [comment] 2020-06-16 06:24
@jeromesimeon where is the PR? I will write the test myself. But we will need to create two files.
- test.js
```
const url = 'https://templates.accordproject.org/archives/acceptance-of-delivery@0.13.2.cta';
const worker = new Worker('./worker.js', { type: 'module' });
worker.postMessage(url);
const templateFromArchive = await Template.fromArchive('acceptance-of-delivery@0.13.2.cta');
worker.onmessage = (event) => {
  const { data } = event;
  expect(data).to.deep.equal(template);
}
```

- worker.js
```
import { Template } from '@accordproject/cicero-core';

onmessage = async (event) => {
  const { data } = event;
  const template = await Template.fromUrl(url);
  postMessage(template);
}
```

**Comment by irmerk** [comment] 2020-06-16 13:10
I believe it has been pushed into a [branch here](https://github.com/accordproject/cicero/tree/parserv2). Confirm that @jeromesimeon?

**Comment by algomaster99** [comment] 2020-06-17 12:10
Once @jeromesimeon confirms, I can write the test myself.

**Comment by jeromesimeon** [comment] 2020-07-05 00:48
Note: this code is effectively gone from the development version of Cicero with the new parser. (See also #278, now closed).

**Comment by jeromesimeon** [comment] 2020-07-24 01:21
@algomaster99 You should be able to try again with cicero `0.21` which doesn't have the troublesome code (the `nunjucks` hack) anymore.

**Comment by jeromesimeon** [comment] 2020-08-26 17:51
Closing this since it should now be fixed. Feel free to reopen if this pops up again.

**Closed by jeromesimeon** 2020-08-26 17:51 UTC
Labels: Type: Need Investigation 🔬
